package de.renatius.poc.springboot.data.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

@Schema(description = "A course taught by a professor")
public record CourseDto(
    @Schema(
            description = "Unique course id, generated by the server; ignored on create",
            example = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            accessMode = Schema.AccessMode.READ_ONLY)
        UUID id,
    @Schema(description = "Course name (required, not blank)", example = "Introduction to Algorithms")
        String name,
    @Schema(description = "Room where the course takes place", example = "B-204") String room,
    @Schema(
            description = "Id of the professor teaching the course (required, must exist)",
            example = "7c9e6679-7425-40de-944b-e07fc1f90ae7")
        UUID professorId) {}
