package de.renatius.poc.springboot.data.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

@Schema(description = "A professor of the university")
public record ProfessorDto(
    @Schema(
            description = "Unique professor id, generated by the server; ignored on create",
            example = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
            accessMode = Schema.AccessMode.READ_ONLY)
        UUID id,
    @Schema(description = "Academic title", example = "Prof. Dr.") String title,
    @Schema(description = "First name", example = "Ada") String firstName,
    @Schema(description = "Last name", example = "Lovelace") String lastName) {}
