package de.renatius.poc.springboot.data.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

@Schema(description = "A student enrolled at the university")
public record StudentDto(
    @Schema(
            description = "Unique student id, generated by the server; ignored on create",
            example = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            accessMode = Schema.AccessMode.READ_ONLY)
        UUID id,
    @Schema(description = "First name", example = "Alan") String firstName,
    @Schema(description = "Last name", example = "Turing") String lastName) {}
