services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=springboot'
      - 'POSTGRES_PASSWORD=springboot'
      - 'POSTGRES_USER=springboot'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
