spring.application.name=restclient
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://tempo.observability:4318/v1/traces}
logging.pattern.correlation=[trace_id=%X{traceId} span_id=%X{spanId}] 
