package de.renatius.poc.springboot.grpc.config;

import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.Descriptors.MethodDescriptor;
import de.renatius.poc.springboot.grpc.v1.AcademicProto;
import java.util.Map;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.ArraySchema;
import io.swagger.v3.oas.models.media.BooleanSchema;
import io.swagger.v3.oas.models.media.IntegerSchema;
import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.tags.Tag;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Documents the gRPC services (served on the gRPC port) in OpenAPI form, derived from the protobuf
 * service and message descriptors. The documented paths follow the gRPC HTTP/2 convention
 * {@code /<package>.<Service>/<Method>}; they are for exploration only.
 */
@Configuration
public class OpenApiConfig {

  @Bean
  public OpenAPI grpcOpenApi() {
    return new OpenAPI()
        .info(
            new Info()
                .title("Academic gRPC API")
                .version("1.0")
                .description(
                    "gRPC services for students, professors and courses, listed from the protobuf"
                        + " definitions. Call them with a gRPC client on the configured gRPC port."))
        .components(
            new Components()
                .addSecuritySchemes(
                    "bearerAuth",
                    new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")));
  }

  private record FieldDoc(String description, Object example) {}

  private static final Map<String, FieldDoc> FIELD_DOCS =
      Map.ofEntries(
          Map.entry("id", new FieldDoc("Unique id (UUID), generated by the server", "3fa85f64-5717-4562-b3fc-2c963f66afa6")),
          Map.entry("first_name", new FieldDoc("First name; as search filter a case-insensitive substring match", "Alan")),
          Map.entry("last_name", new FieldDoc("Last name; as search filter a case-insensitive substring match", "Turing")),
          Map.entry("title", new FieldDoc("Academic title", "Prof. Dr.")),
          Map.entry("name", new FieldDoc("Course name; as search filter a case-insensitive substring match", "Introduction to Algorithms")),
          Map.entry("room", new FieldDoc("Room where the course takes place", "B-204")),
          Map.entry("professor_id", new FieldDoc("Id (UUID) of the professor teaching the course; must exist", "7c9e6679-7425-40de-944b-e07fc1f90ae7")),
          Map.entry("page", new FieldDoc("Zero-based page index (request: paging options, response: current page)", 0)),
          Map.entry("size", new FieldDoc("Page size", 20)),
          Map.entry("sort_by", new FieldDoc("Name of the field to sort by", "lastName")),
          Map.entry("sort_direction", new FieldDoc("Sort direction: SORT_DIRECTION_ASC or SORT_DIRECTION_DESC", "SORT_DIRECTION_ASC")),
          Map.entry("total_elements", new FieldDoc("Total number of matching elements over all pages", 42)),
          Map.entry("total_pages", new FieldDoc("Total number of pages", 3)),
          Map.entry("students", new FieldDoc("Students on this page", null)),
          Map.entry("professors", new FieldDoc("Professors on this page", null)),
          Map.entry("courses", new FieldDoc("Courses on this page", null)));

  private static final Map<String, String> OPERATION_DOCS =
      Map.of(
          "Create", "Creates a new %s. The id is generated by the server. Required fields are validated; for courses the referenced professor must exist.",
          "Get", "Returns the %s with the given id.",
          "Update", "Replaces all mutable fields of an existing %s (full update; every field is required).",
          "Delete", "Permanently deletes the %s with the given id and returns an empty message.",
          "Search", "Returns a paginated list of %ss. Optional filters are case-insensitive substring matches; omitted filters are ignored.");

  @Bean
  public OpenApiCustomizer grpcServicesCustomizer() {
    return openApi -> {
      if (openApi.getComponents() == null) {
        openApi.setComponents(new Components());
      }
      AcademicProto.getDescriptor()
          .getMessageTypes()
          .forEach(message -> openApi.getComponents().addSchemas(message.getName(), messageSchema(message)));
      AcademicProto.getDescriptor()
          .getServices()
          .forEach(
              service -> {
                String entity = service.getName().replace("Service", "");
                openApi.addTagsItem(
                    new Tag()
                        .name(service.getName())
                        .description("gRPC service %s: manage %ss".formatted(service.getFullName(), entity.toLowerCase())));
                service.getMethods().forEach(method -> addOperation(openApi, service.getName(), entity, method));
              });
    };
  }

  private void addOperation(OpenAPI openApi, String serviceName, String entity, MethodDescriptor method) {
    String verb = method.getName().replace(entity, "");
    String description = OPERATION_DOCS.getOrDefault(verb, "gRPC call " + method.getName()).formatted(entity.toLowerCase());
    Operation operation =
        new Operation()
            .addTagsItem(serviceName)
            .operationId(serviceName + "_" + method.getName())
            .summary(method.getName() + " (" + method.getFullName() + ")")
            .description(description + " Invoke with a gRPC client on the gRPC port, not via HTTP.")
            .requestBody(
                new RequestBody()
                    .required(true)
                    .content(jsonContent(ref(method.getInputType()))))
            .responses(responses(verb, method));
    openApi.path("/" + method.getService().getFullName() + "/" + method.getName(), new PathItem().post(operation));
  }

  private ApiResponses responses(String verb, MethodDescriptor method) {
    ApiResponses responses =
        new ApiResponses()
            .addApiResponse(
                "0 OK",
                new ApiResponse()
                    .description("Call succeeded")
                    .content(jsonContent(ref(method.getOutputType()))));
    if (!"Search".equals(verb) && !"Create".equals(verb)) {
      responses.addApiResponse("5 NOT_FOUND", error("No entity exists with the given id"));
    }
    if (!"Get".equals(verb) && !"Delete".equals(verb)) {
      responses.addApiResponse("3 INVALID_ARGUMENT", error("Invalid request: missing or blank required field, malformed id, or unknown referenced id"));
    } else {
      responses.addApiResponse("3 INVALID_ARGUMENT", error("Malformed id"));
    }
    responses.addApiResponse("13 INTERNAL", error("Unexpected server error"));
    return responses;
  }

  private static ApiResponse error(String description) {
    return new ApiResponse().description(description);
  }

  private static Content jsonContent(Schema<?> schema) {
    return new Content().addMediaType("application/grpc+proto", new MediaType().schema(schema));
  }

  private static Schema<?> ref(Descriptor type) {
    return new Schema<>().$ref("#/components/schemas/" + type.getName());
  }

  private static Schema<?> messageSchema(Descriptor message) {
    ObjectSchema schema = new ObjectSchema();
    schema.setDescription("Protobuf message " + message.getFullName());
    message.getFields().forEach(field -> schema.addProperty(field.getName(), fieldSchema(field)));
    return schema;
  }

  private static Schema<?> fieldSchema(FieldDescriptor field) {
    FieldDoc doc = FIELD_DOCS.get(field.getName());
    Schema<?> base =
        switch (field.getJavaType()) {
          case STRING -> new StringSchema();
          case INT -> new IntegerSchema();
          case LONG -> new IntegerSchema().format("int64");
          case BOOLEAN -> new BooleanSchema();
          case ENUM -> {
            StringSchema enumSchema = new StringSchema();
            field.getEnumType().getValues().forEach(v -> enumSchema.addEnumItem(v.getName()));
            yield enumSchema;
          }
          case MESSAGE -> ref(field.getMessageType());
          default -> new ObjectSchema();
        };
    Schema<?> result = field.isRepeated() ? new ArraySchema().items(base) : base;
    if (doc != null && field.getJavaType() != FieldDescriptor.JavaType.MESSAGE) {
      result.setDescription(doc.description());
      if (doc.example() != null && !field.isRepeated()) {
        result.setExample(doc.example());
      }
    } else if (doc != null && field.isRepeated()) {
      result.setDescription(doc.description());
    }
    return result;
  }
}
